blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions 
    url: https://github.com/Azure/logicapps/discussions
    about: Please ask and answer questions in the discussions section