trigger: none

pr: none

variables:
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: dev
# TODO: Replace 'value' with the name of your Azure service connection
- name: devServiceConnection
  value: 'NAME OF AZURE SERVICE CONNECTION IN AZURE DEVOPS'

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        # TODO: Adapt 'sourceFolder' to your repository structure, default is 'deploy' and is equivalent to '$(Build.SourcesDirectory)/deploy'
        sourceFolder: 'deploy'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: $(devEnvironment)
      serviceConnection: $(devServiceConnection)
