trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)

jobs:
- job: logic_app_build
  displayName: 'Build and validate logic app'
  steps:
  - template: templates/template-build-logicapp.yml
    parameters:
      workingDirectory: $(workingDirectory)
      configuration: Debug
