# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (container) Build and Deploy Logic App. 

env:
  AZURE_LOGICAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '3.1.301'    # set this to the dotnet version to use
  RG_LA: 'your-la-rg'
  RG_CON: 'your-con-rg'
  LA_NAME: 'your-la-name'
  Cont_Image: 'your-cont-image'
  Cont_Tag: 'your-tag'
  acrUsername: 'your-acr-name'

on:
  - workflow_dispatch 

jobs:
   logic_app_build: 
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

     #build container image
    - name: Generate Connections
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Scripts/Generate-Connections.ps1 -resourceGroup '${{ env.RG_CON }}'
        azPSVersion: latest

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.acrUsername }}.azurecr.io
        username: ${{ env.acrUsername }}
        password: ${{secrets.ACRPASSWORD}}

    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        docker build . -t  ${{ env.acrUsername }}.azurecr.io/${{ env.Cont_Image }}:${{ env.Cont_Tag }}
        docker push  ${{ env.acrUsername }}.azurecr.io/${{ env.Cont_Image }}:${{ env.Cont_Tag }}

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: ${{ env.LA_NAME }}
        image: '${{ env.acrUsername }}''.azurecr.io/${{ env.Cont_Image }}:${{ env.Cont_Tag }}'
    #- name: 'use the published functionapp url in upcoming steps'
    #  run: |
    #    echo "${{ steps.fa.outputs.app-url }}"