trigger: none

pr: none

variables:
- name: devEnvironment
  value: dev
# TODO: provide an email for the ExampleWorkflow to send mail to
- name: toEmailAddress
  value: ''

resources:
  pipelines:
  - pipeline: ciPipeline
    # TODO: Update with the name of your CI pipeline
    source: ''
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/vars-iac.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-18.04
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionAppContainer@1
            displayName: 'Update logic app container'
            inputs:
              azureSubscription: $(devServiceConnection)
              appName: '$(logicAppName)'
              imageName: '$(acrName).azurecr.io/$(logicAppContainerName):$(resources.pipeline.ciPipeline.RunId)'
              appsettings: '-emailAddress $(toEmailAddress)'
