name: Sync issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]
  
jobs:
  alert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: '${{ secrets.SYNC_SECRET }}'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          ado_organization: 'msazure'
          ado_project: 'One'
          ado_area_path: "One\\Azure\\LogicApps"
          ado_iteration_path: "One\\Custom\\Azure\\LogicApps"
          ado_wit: 'Bug'
          ado_new_state: 'New'
          ado_active_state: 'Active'
          ado_close_state: 'Done'
          log_level: 100
